api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: $ACME_EMAIL
      dnschallenge:
        provider: cloudflare
        delaybeforecheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      caServer:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
